apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-was-deployment
  labels:
    tier: was
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: was
  template:
    metadata:
      labels:
        tier: was
    spec:
      containers:
      - name: store-container
        image: asia.gcr.io/terraform-tae/store:1
        ports:
        - containerPort: 8080
        resources:
          requests: 
            memory: "100Mi"
            cpu: "250m"
          limits:   
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: store-svc
spec:
  selector:
    tier: was
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
