apiVersion: apps/v1
kind: Deployment
metadata:
  name: goods-was-deployment
  labels:
    tier: was
spec:
  replicas: 3 # pod 개수 지정 
  selector:
    matchLabels:
      tier: was
  template:
    metadata:
      labels:
        tier: was
    spec:
      containers:
      - name: goods-container
        image: asia.gcr.io/terraform-tae/goods:26
        ports:
        - containerPort: 8080
        resources:
          requests: ## 오토파일럿 모드에서 없으면 에러 발생 
            memory: "100Mi"
            cpu: "250m"
          limits: ## limit이 없으면 오토스케일링 문제 발생  
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: goods-svc
spec:
  selector:
    tier: was
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
