apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-was-deployment
  labels:
    tier: was
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: was
  template:
    metadata:
      labels:
        tier: was
    spec:
      nodeSelector:
        node: service       
      containers:
      - name: store-container
<<<<<<< HEAD
        image: asia.gcr.io/terraform-tae/goods:1
=======
        image: asia.gcr.io/terraform-tae/store:26
>>>>>>> 864fc3cae2a5c81b0baf936bab8fbbdf58407b5c
        ports:
        - containerPort: 8080
        resources:
          requests: 
            memory: "100Mi"
            cpu: "250m"
          limits:   
            cpu: "500m"
