apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-was-deployment
  labels:
    tier: was
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: was
  template:
    metadata:
      labels:
        tier: was
    spec:
      nodeSelector:
        node: service       
      containers:
      - name: store-container
        image: asia.gcr.io/terraform-tae/store:23
        ports:
        - containerPort: 8080
        resources:
          requests: 
            memory: "100Mi"
            cpu: "250m"
          limits:   
            cpu: "500m"
