apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-was-deployment
  labels:
    tier: was
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: was
  template:
    metadata:
      labels:
        tier: was
    spec:
      nodeSelector:
        node: app       
      containers:
      - name: kf-container
        image: asia.gcr.io/class-mino-01/kf-was:26
        ports:
        - containerPort: 8080
        resources:
          requests: 
            memory: "100Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"

