apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-web-deployment
  labels:
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      nodeSelector:
        node: app       
      containers:
      - name: kf-container
        image: asia.gcr.io/class-mino-01/kfimg:4
        ports:
        - containerPort: 8080
        resources:
          requests: 
            memory: "100Mi"
            cpu: "250m"
          limits:   
            cpu: "500m"

