apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-web-deployment
  labels:
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      nodeSelector:
        node: app
      containers:
      - name: kf-web-container
        image: asia.gcr.io/class-mino-01/kf-web:6
        ports:
        - containerPort: 80
